<?php
	/*
	define("DB_HOST","localhost");
	define("DB_USER","evaDocTESOEM");
	define("DB_PASSWORD","@@evaDocTESOEM#1@@");
	define("DB_DATABASE","evaluaciondocenteM");
	*/
	define("DB_HOST","localhost");
	define("DB_USER","root");
	define("DB_PASSWORD","root");
	define("DB_DATABASE","evaluaciondocente");
?>
